import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ReduxProvider } from "@/components/provider/redux-provider";
import { Toaster } from "@/components/ui/toaster";
import { useLoadUserQuery } from "../redux/features/api/apiSlice";
import CustomUserLoad from "@/components/provider/custom-user-load";
import { ModalProvider } from "@/components/provider/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          <Toaster />
          <ModalProvider />
          {/* @ts-ignore */}
          <CustomUserLoad>{children}</CustomUserLoad>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
